`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 07/20/2023 11:13:55 PM
// Design Name: 
// Module Name: bpskmodul
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////



// -------------------------------------------------------------
// 
// File Name: hdlsrc/bpsk1/BPSK_Modulator_Baseband1.v
// Created: 2023-07-20 17:38:01
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BPSK_Modulator_Baseband1
// Source Path: bpsk1/BPSK Modulator Baseband1
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BPSK_Modulator_Baseband1
          (in0,
           out0_re,
           out0_im);


  input   [15:0] in0;  // uint16
  output  signed [15:0] out0_re;  // sfix16_En15
  output  signed [15:0] out0_im;  // sfix16_En15


  wire bpsk_sel;
  wire signed [15:0] inphase_val0;  // sfix16_En15
  wire signed [15:0] inphase_val1;  // sfix16_En15
  wire signed [15:0] inphase;  // sfix16_En15
  wire signed [15:0] quadrature;  // sfix16_En15


  assign bpsk_sel = in0[0];



  assign inphase_val0 = 16'sb0111111111111111;



  assign inphase_val1 = 16'sb1000000000000000;



  assign inphase = (bpsk_sel == 1'b0 ? inphase_val0 :
              inphase_val1);



  assign out0_re = inphase;

  assign quadrature = 16'sb0000000000000000;



  assign out0_im = quadrature;

endmodule  // BPSK_Modulator_Baseband1


