`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 07/20/2023 11:25:19 PM
// Design Name: 
// Module Name: bpskdemodul
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////



// 
// File Name: hdlsrc/bpsk1/BPSK_Demodulator_Baseband1.v
// Created: 2023-07-20 17:38:01
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BPSK_Demodulator_Baseband1
// Source Path: bpsk1/BPSK Demodulator Baseband1
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BPSK_Demodulator_Baseband1
          (in0_re,
           in0_im,
           out0);


  input   signed [15:0] in0_re;  // sfix16_En15
  input   signed [15:0] in0_im;  // sfix16_En15
  output  [7:0] out0;  // uint8


  wire inphase_lt_zero;
  wire inphase_eq_zero;
  wire quadrature_eq_zero;
  wire [2:0] decisionLUTaddr;  // ufix3
  wire [0:7] DirectLookupTable_1;  // ufix1 [8]
  wire hardDecision;  // ufix1


  assign inphase_lt_zero = in0_re < 16'sb0000000000000000;



  assign inphase_eq_zero = in0_re == 16'sb0000000000000000;



  assign quadrature_eq_zero = in0_im == 16'sb0000000000000000;



  assign decisionLUTaddr = {inphase_lt_zero, inphase_eq_zero, quadrature_eq_zero};



  assign DirectLookupTable_1[0] = 1'b0;
  assign DirectLookupTable_1[1] = 1'b0;
  assign DirectLookupTable_1[2] = 1'b1;
  assign DirectLookupTable_1[3] = 1'b0;
  assign DirectLookupTable_1[4] = 1'b1;
  assign DirectLookupTable_1[5] = 1'b1;
  assign DirectLookupTable_1[6] = 1'b1;
  assign DirectLookupTable_1[7] = 1'b0;
  assign hardDecision = DirectLookupTable_1[decisionLUTaddr];



  assign out0 = {7'b0, hardDecision};



endmodule  // BPSK_Demodulator_Baseband1

